export BUILT_PRODUCTS_DIR="/Users/tonimwhite/Library/Developer/Xcode/DerivedData/iTrackGames-civkrwelewbaekfoqkndtppmcudq/Build/Products/Debug-iphonesimulator"
export CURRENT_ARCH="i386"
export OBJECT_FILE_DIR_normal="/Users/tonimwhite/Library/Developer/Xcode/DerivedData/iTrackGames-civkrwelewbaekfoqkndtppmcudq/Build/Intermediates/iTrackGames.build/Debug-iphonesimulator/iTrackGamesTests.build/Objects-normal"
export OBJROOT="/Users/tonimwhite/Library/Developer/Xcode/DerivedData/iTrackGames-civkrwelewbaekfoqkndtppmcudq/Build/Intermediates"
export SRCROOT="/Users/tonimwhite/itrackgames-ios/iTrackGames"
