export BUILT_PRODUCTS_DIR="/Users/amanda.chappell/Library/Developer/Xcode/DerivedData/iTrackGames-etdhbpllyjufhedjmjblcecdyuzw/Build/Products/Debug-iphonesimulator"
export CURRENT_ARCH="i386"
export OBJECT_FILE_DIR_normal="/Users/amanda.chappell/Library/Developer/Xcode/DerivedData/iTrackGames-etdhbpllyjufhedjmjblcecdyuzw/Build/Intermediates/iTrackGames.build/Debug-iphonesimulator/iTrackGamesTests.build/Objects-normal"
export OBJROOT="/Users/amanda.chappell/Library/Developer/Xcode/DerivedData/iTrackGames-etdhbpllyjufhedjmjblcecdyuzw/Build/Intermediates"
export SRCROOT="/Users/amanda.chappell/Documents/rails/itrackgames-ios/iTrackGames"
